version: '3.8'

services:
  admin-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/admin-ui
      - SESSION_SECRET=your-secret-key-change-in-production
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_TRACING_ENABLED=false
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=admin-ui
    volumes:
      - mongo_data:/data/db
      - ./scripts/data-setup:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mongo_data: 